### ISSUE TITLE
Pass along all parameters?

### ISSUE THREAD

**Issue by kylegibson-rldatix** [mneudert/vagrant-devcommands#3]
Hello!

Is there a way to pass along all parameters?

For example

```
command 'server',
  script: 'python server.py',
  tty: true
```

And then

`vagrant run server do_a_thing --super`

would automatically run (on the guest):

`python server do_a_thing --super`

**Comment by mneudert** [comment]
Right now you can only wrap the parameters in a parameter:

```ruby
command 'server',
    script: 'python server.py %{arguments}',
    parameters: {arguments: {optional: true}}
```
```shell
vagrant run server --arguments='do_a_thing --super'
```

That should work but feels a bit clunky.

I like the option to have some sort of a "catch all unknown parameters"-parameter. Do you have any idea how that configuration could look like? I am thinking of something like having `catchall: true` added to the individual parameter spec but that may be a bit unintuitive...

**Comment by kylegibson-rldatix** [comment]
Options I thought of: `passthru: true` or `alias: true`

**Comment by mneudert** [comment]
Just an example command (for documentation and perhaps later include in README) which I think could really benefit from this feature:

```ruby
command 'sql-dump',
    desc: 'creates a dump of the development database',
    parameters: {
      username: {default: 'root'},
      password: {default: 'changeme'},
      database: {default: 'development'},
      dump_options: { /* ??? */ }
    },
    script: %(
        [ -f /vagrant/sqldumps/%{database}.sql ] \
        && mysql \
               -u%{username} \
               -p%{password} \
               %{database}
               %{dump_options} \
           < /vagrant/sqldumps/%{database}.sql \
        || true
    )
```

And then I want to be able to run:

```shell
vagrant run sql-dump --username='developer' --password='insecure' --no-create-db --no-create-info
```

One would expect by defining `dump_options` properly that `--no-create-db --no-create-info` would get interpolated at that position if there are any unknown arguments given.

**Comment by kylegibson-rldatix** [comment]
The above example would satisfy the goals I'm trying to achieve. What can I do to help implement this?

**Comment by mneudert** [comment]
You just had to wait a bit :D

There are still some rough edges but if you try out the current master branch you should be able to use the new option:

```shell
git clone git@github.com:mneudert/vagrant-devcommands.git
cd vagrant-devcommands
gem build vagrant-devcommands.gemspec
vagrant plugin install vagrant-devcommands-0.13.0.dev.gem
```

The commands are written from memory so they might not be perfect but should help you get the development version running for a testdrive. Once I have added tests for the various option combinations - like the combination of `escape` and `passthru` or handling non-optional `passthru` parameter - it should be ready for release.

Unless you wish to get some modifications to better suit your intended usage.

**Comment by mneudert** [comment]
:shipit:
